name: CI - Estoque Spring API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: test-secret-ci
      JWT_EXPIRATION_HOURS: ${{ secrets.JWT_EXPIRATION_HOURS }}

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Rodar testes
        run: mvn test

      - name: Gerar build
        run: mvn clean package